export const DEFAULT_NATIVE_EMBEDDING_MODEL = "Xenova/all-MiniLM-L6-v2";
export const DEFAULT_NATIVE_EMBEDDING_DIMENSIONS = 384;
export const DEFAULT_NATIVE_EMBEDDING_IDLE_UNLOAD_MS = 5 * 60 * 1000;
export const EDGE_NATIVE_EMBEDDING_IDLE_UNLOAD_MS = 30 * 1000;
