import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { argValue, repoRoot } from "./lib";

const USAGE = `Usage: bun .agents/skills/benchmarking/scripts/sample-questions.ts --total <n> --seed <n> [--out <file>]

Draws a LongMemEval question sample whose question-type mix matches the full set. Each type gets
total x (its share of the set), rounded by largest remainder; questions within a type are chosen by a
seeded shuffle, so the same total and seed always give the same list. Prints the list, or writes it
to --out for MemoryBench's --question-ids-file, with the method and per-type counts as comments.`;

const QUESTIONS_DIR = join(repoRoot, "memorybench/data/benchmarks/longmemeval/datasets/questions");

interface Question {
	readonly id: string;
	readonly type: string;
}

function mulberry32(seed: number): () => number {
	let state = seed >>> 0;
	return () => {
		state = (state + 0x6d2b79f5) >>> 0;
		let t = state;
		t = Math.imul(t ^ (t >>> 15), t | 1);
		t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
		return ((t ^ (t >>> 14)) >>> 0) / 4_294_967_296;
	};
}

export function allocate(counts: ReadonlyMap<string, number>, total: number): Map<string, number> {
	const size = [...counts.values()].reduce((sum, count) => sum + count, 0);
	if (total > size) throw new Error(`Cannot sample ${total} of ${size} questions`);
	const types = [...counts.keys()].sort();
	const exact = types.map((type) => ({ type, share: (total * (counts.get(type) ?? 0)) / size }));
	const allocation = new Map(exact.map(({ type, share }) => [type, Math.floor(share)]));
	let remaining = total - [...allocation.values()].reduce((sum, count) => sum + count, 0);
	const byRemainder = [...exact].sort(
		(a, b) => b.share - Math.floor(b.share) - (a.share - Math.floor(a.share)) || a.type.localeCompare(b.type),
	);
	for (const { type } of byRemainder) {
		if (remaining === 0) break;
		allocation.set(type, (allocation.get(type) ?? 0) + 1);
		remaining--;
	}
	return allocation;
}

export function sampleQuestions(questions: readonly Question[], total: number, seed: number): Question[] {
	const byType = new Map<string, Question[]>();
	for (const question of [...questions].sort((a, b) => a.id.localeCompare(b.id))) {
		byType.set(question.type, [...(byType.get(question.type) ?? []), question]);
	}
	const allocation = allocate(new Map([...byType].map(([type, list]) => [type, list.length])), total);
	const random = mulberry32(seed);
	const selected: Question[] = [];
	for (const type of [...byType.keys()].sort()) {
		const pool = [...(byType.get(type) ?? [])];
		for (let index = pool.length - 1; index > 0; index--) {
			const swap = Math.floor(random() * (index + 1));
			[pool[index], pool[swap]] = [pool[swap], pool[index]];
		}
		selected.push(...pool.slice(0, allocation.get(type) ?? 0));
	}
	return selected.sort((a, b) => a.id.localeCompare(b.id));
}

function loadQuestions(): Question[] {
	return readdirSync(QUESTIONS_DIR)
		.filter((file) => file.endsWith(".json"))
		.map((file) => {
			const item = JSON.parse(readFileSync(join(QUESTIONS_DIR, file), "utf8")) as {
				question_id: string;
				question_type: string;
			};
			return { id: item.question_id, type: item.question_type };
		});
}

function main(): void {
	const args = process.argv.slice(2);
	const total = Number(argValue(args, "--total"));
	const seed = Number(argValue(args, "--seed"));
	if (!Number.isInteger(total) || total < 1 || !Number.isInteger(seed) || args.includes("--help")) {
		console.log(USAGE);
		process.exit(args.includes("--help") ? 0 : 1);
	}
	const questions = loadQuestions();
	const selected = sampleQuestions(questions, total, seed);
	const counts = new Map<string, number>();
	for (const question of selected) counts.set(question.type, (counts.get(question.type) ?? 0) + 1);
	const abstention = selected.filter((question) => question.id.endsWith("_abs")).length;
	const header = [
		`# LongMemEval sample: ${selected.length} of ${questions.length} questions, proportional to question type, seed ${seed}`,
		"# Generated by .agents/skills/benchmarking/scripts/sample-questions.ts",
		...[...counts].sort(([a], [b]) => a.localeCompare(b)).map(([type, count]) => `# ${type}: ${count}`),
		`# abstention (_abs) questions included: ${abstention}`,
	];
	const body = `${[...header, ...selected.map((question) => question.id)].join("\n")}\n`;
	const out = argValue(args, "--out");
	if (out) writeFileSync(out, body);
	else process.stdout.write(body);
}

if (import.meta.main) main();
