#!/usr/bin/env bun

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const packageRoot = join(__dirname, "..");
const pluginDistPath = join(packageRoot, "..", "plugin", "dist", "signet.mjs");
const bundleSourcePath = join(packageRoot, "src", "plugin-bundle.ts");

if (!existsSync(pluginDistPath)) {
	console.warn(`[embed-plugin] Plugin bundle not found at ${pluginDistPath} — skipping embed`);
	process.exit(0);
}

const pluginSource = readFileSync(pluginDistPath, "utf-8");
const escaped = pluginSource.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const output = `/**
 * Bundled OpenCode plugin content
 *
 * Auto-generated by scripts/embed-plugin.ts — do not edit manually.
 * Re-run the build to regenerate from ../plugin/dist/signet.mjs
 */

export const PLUGIN_BUNDLE = \`${escaped}\`;
`;

writeFileSync(bundleSourcePath, output);
console.log(`[embed-plugin] Embedded ${pluginDistPath} → src/plugin-bundle.ts`);
