import { resolveDefaultBasePath } from "@signet/core";
import { getDbAccessor } from "./db-accessor";
import { dbOwnerQuery, dbOwnerSourcePurge, dbOwnerTransaction, runDbOwnerDomainOperation } from "./db-owner-runtime";
import { purgeTranscriptImportSourceInTx } from "./transcript-import-commit";
import { purgeTranscriptImportFilesystem } from "./transcript-import-worker";
import { purgeSourceOwnedRowsInTx, type PurgeSourceOwnedRowsInput } from "./source-purge-tx";
import { withTranscriptImportOperationLock } from "./transcript-import-operation-lock";

export { purgeSourceOwnedRowsInTx } from "./source-purge-tx";
export type { PurgeSourceOwnedRowsInput } from "./source-purge-tx";

const TRANSCRIPT_IMPORT_PURGE_JOB_SQL =
	"UPDATE source_import_jobs SET state = 'cancelled', generation = generation + 1, control_request = NULL, lease_token = NULL, lease_expires_at = NULL, error = COALESCE(error, 'source deleted'), updated_at = ? WHERE agent_id = ? AND state NOT IN ('completed','completed_with_rejections','cancelled') AND EXISTS (SELECT 1 FROM source_import_files WHERE source_import_files.job_id = source_import_jobs.id AND source_import_files.agent_id = source_import_jobs.agent_id AND source_import_files.source_id = ?)";
const TRANSCRIPT_IMPORT_PURGE_RECORD_SQL =
	"UPDATE source_import_records SET status = 'cancelled', rejection_code = 'source_deleted', updated_at = ? WHERE agent_id = ? AND status = 'pending' AND EXISTS (SELECT 1 FROM source_import_files WHERE source_import_files.id = source_import_records.file_id AND source_import_files.agent_id = source_import_records.agent_id AND source_import_files.source_id = ?)";

/**
 * Invalidate import leases before touching canonical files. The owner-side
 * generation change closes the gap between a worker guard and its DB commit.
 */
async function invalidateTranscriptImportSource(input: PurgeSourceOwnedRowsInput, agentId: string): Promise<void> {
	const timestamp = new Date().toISOString();
	await dbOwnerTransaction(
		[
			{
				sql: TRANSCRIPT_IMPORT_PURGE_JOB_SQL,
				params: [timestamp, agentId, input.sourceId],
				result: "run" as const,
			},
			{
				sql: TRANSCRIPT_IMPORT_PURGE_RECORD_SQL,
				params: [timestamp, agentId, input.sourceId],
				result: "run" as const,
			},
		],
		{ operation: "sources.import.invalidate", lane: "write" },
	);
}

export async function purgeSourceOwnedRows(input: PurgeSourceOwnedRowsInput): Promise<number> {
	return await withTranscriptImportOperationLock("transcript-import", () => purgeSourceOwnedRowsUnlocked(input));
}

async function purgeSourceOwnedRowsUnlocked(input: PurgeSourceOwnedRowsInput): Promise<number> {
	const sourceId = input.sourceId.trim();
	if (!sourceId) return 0;
	const agentId = input.agentId ?? "default";
	let managedPaths: string[] = [];
	try {
		managedPaths = await runDbOwnerDomainOperation(getDbAccessor(), {
			runWithOwner: async () =>
				(
					await dbOwnerQuery<Array<{ managed_path: string }>>(
						{
							sql: `SELECT managed_path FROM source_import_files WHERE ${input.agentId ? "agent_id = ? AND " : ""}source_id = ?`,
							params: input.agentId ? [input.agentId, sourceId] : [sourceId],
							result: "all",
							readonly: true,
						},
						{ operation: "sources.import.purge-paths", lane: "read" },
					)
				).map((row) => row.managed_path),
			runInline: ({ read }) =>
				read((db) =>
					(
						db
							.prepare(
								`SELECT managed_path FROM source_import_files WHERE ${input.agentId ? "agent_id = ? AND " : ""}source_id = ?`,
							)
							.all(...(input.agentId ? [input.agentId] : []), sourceId) as Array<{ managed_path: string }>
					).map((row) => row.managed_path),
				),
		});
	} catch {
		// Older databases do not have import ledgers.
	}

	await invalidateTranscriptImportSource({ sourceId }, agentId);
	// Source ids are normally generated by the import route, but ledger paths
	// remain independently gated by purgeTranscriptImportFilesystem.
	if (!sourceId.includes("/") && !sourceId.includes("\\") && !sourceId.includes("..")) {
		await purgeTranscriptImportFilesystem(resolveDefaultBasePath(), sourceId, input.agentId, managedPaths);
	}

	const result = await runDbOwnerDomainOperation(getDbAccessor(), {
		runWithOwner: async () =>
			await dbOwnerSourcePurge({ agentId: input.agentId, sourceId }, { operation: "sources.purge", lane: "write" }),
		runInline: ({ write }) =>
			write((db) => ({
				purged:
					purgeSourceOwnedRowsInTx(db, { sourceId, agentId: input.agentId }) +
					purgeTranscriptImportSourceInTx(db, agentId, sourceId),
			})),
	});
	return typeof result === "number" ? result : result.purged;
}
