/**
 * The dashboard's shared icon surface.
 *
 * Keep the local names used by the UI components stable while sourcing every
 * application glyph from MingCute's Regular set. This also gives the icon
 * system one place to tune later without changing component behavior.
 */
export {
	AlertRegular as AlertCircle,
	AlertRegular as TriangleAlert,
	AlertRegular as TriangleAlertIcon,
	ArrowDownRegular as ArrowDownIcon,
	ArrowLeftRegular as ArrowLeft,
	ArrowRightRegular as ArrowRight,
	CheckRegular as Check,
	CheckRegular as CheckIcon,
	CheckCircleRegular as CheckCircle,
	CheckCircleRegular as CircleCheckIcon,
	CircleDashRegular as CircleIcon,
	CloseCircleRegular as OctagonXIcon,
	CloseRegular as X,
	CloseRegular as XIcon,
	CloudRegular as Cloud,
	CopyRegular as Copy,
	DeleteRegular as Trash2,
	DownRegular as ChevronDown,
	DownSmallRegular as ChevronDownIcon,
	DownloadRegular as Download,
	ExpandPlayerRegular as Maximize2,
	ExternalLinkRegular as ExternalLink,
	EyeCloseRegular as EyeOff,
	EyeRegular as Eye,
	FileImportRegular as Import,
	FileInfoRegular as FileText,
	FileRegular as File,
	FilterRegular as Filter,
	FolderOpenRegular as FolderOpen,
	FolderRegular as Folder,
	GitBranchRegular as GitBranch,
	GlobeRegular as Globe,
	Key1Regular as KeyRound,
	LeftRegular as ChevronLeft,
	LeftSmallRegular as ChevronLeftIcon,
	Link2Regular as Link2,
	Loading2Regular as Loader2,
	Loading2Regular as Loader2Icon,
	MenuRegular as Menu,
	Message1Regular as MessageCircle,
	MindMapRegular as Network,
	MonitorRegular as Monitor,
	MoonRegular as Moon,
	ChartBarRegular as Activity,
	InformationRegular as InfoIcon,
	PlayRegular as Play,
	PlusRegular as Plus,
	Refresh1Regular as RefreshCw,
	Refresh1Regular as RefreshAnticlockwise,
	Refresh1Regular as RotateCcw,
	Refresh1Regular as RotateCw,
	RightRegular as ChevronRight,
	RightSmallRegular as ChevronRightIcon,
	RightSmallRegular as ChevronRightSmall,
	RobotRegular as Bot,
	SearchRegular as Search,
	Settings1Regular as Settings,
	ShieldRegular as ShieldCheck,
	SunRegular as Sun,
	TerminalBoxRegular as SquareTerminal,
	UnlinkRegular as Unlink,
	UploadRegular as Upload,
	UpSmallRegular as ChevronUpIcon,
	User1Regular as UserRound,
} from "@mingcute/react/core-regular";
