/**
 * @signet/core - Markdown utilities
 *
 * Functions for managing Signet blocks in markdown files.
 * A Signet block is an auto-generated section delimited by HTML comments
 * that is injected into harness-specific config files (CLAUDE.md, AGENTS.md, etc.)
 */

export const SIGNET_BLOCK_START = "<!-- SIGNET:START -->";
export const SIGNET_BLOCK_END = "<!-- SIGNET:END -->";

/**
 * Build the Signet system block injected into all generated harness files.
 *
 * This block ensures agents always know how to use Signet regardless of
 * whether the user's source AGENTS.md was created from template or pre-existed.
 * It provides:
 * - Overview of key files in the Signet workspace
 * - Dashboard URL
 * - Memory command usage (/remember, /recall)
 * - Secrets command usage
 */
export function buildSignetBlock(workspace = "$SIGNET_WORKSPACE"): string {
	const root = normalizeWorkspace(workspace);
	return `${SIGNET_BLOCK_START}
Signet Agent System
===

Your identity and memory are managed by Signet, a portable agent identity
system. It gives you durable identity, working memory, and memory retrieval
across different AI platforms (Claude Code, OpenCode, Cursor, etc.).

You are operating inside a layered memory runtime. The markdown files in
your workspace are important prompt surfaces, but they are not the whole
system. Treat \`MEMORY.md\` as a rendered working-memory head over deeper
temporal and structured state, not as the canonical source of truth.

Key files in your Signet workspace (\`${root}/\`):
- \`${root}/agent.yaml\` — Configuration
- \`${root}/AGENTS.md\` — Instructions and operating rules
- \`${root}/SOUL.md\` — Personality, values, and temperament
- \`${root}/IDENTITY.md\` — Agent identity
- \`${root}/USER.md\` — User profile and relationship context
- \`${root}/MEMORY.md\` — Auto-generated working memory summary
- \`${root}/SIGNET-ARCHITECTURE.md\` — How the memory pipeline works (read if asked)

Dashboard: http://localhost:3850

Memory
---

You have access to persistent memory via Signet:

\`\`\`bash
signet remember "User prefers dark mode and vim keybindings"
signet recall "user preferences"
\`\`\`

Memory is automatically loaded at session start. Important context is
summarized in \`${root}/MEMORY.md\`.

Identity Stewardship
---

Treat the files in your Signet workspace as distinct layers of context:

- \`AGENTS.md\` — how you operate
- \`SOUL.md\` — how you sound, what you value, and your temperament
- \`IDENTITY.md\` — who you are
- \`USER.md\` — who the user is and how to relate to them
- \`MEMORY.md\` — episodic and operational context generated by Signet

You should actively maintain \`AGENTS.md\`, \`SOUL.md\`, \`IDENTITY.md\`,
and \`USER.md\` as durable context. These files are always editable by
you. Update them when you learn stable truths that belong there. Prefer
additive, intentional refinement over impulsive rewrites. Preserve
continuity unless the user explicitly wants a deeper identity rewrite.

Do not edit \`MEMORY.md\` manually. It is system-managed and regenerated
by Signet.

Secrets
---

API keys and tokens are stored securely in Signet. Agents never see
raw values — secrets are injected into subprocesses as environment
variables with output automatically redacted.

- \`mcp__signet__secret_list\` — discover available secret names
- \`mcp__signet__secret_exec\` — run a command with secrets injected as env vars

Example: to use an API key stored as "OPENAI_API_KEY", call \`mcp__signet__secret_exec\`
with \`command: "curl -H \\"Authorization: Bearer $OPENAI_API_KEY\\" ..."\`
and \`secrets: { "OPENAI_API_KEY": "OPENAI_API_KEY" }\`.

Knowledge Graph
---

Signet maintains a knowledge graph of entities extracted from your
conversations. Use these MCP tools to explore it:

- \`mcp__signet__knowledge_expand\` — drill into an entity's aspects, attributes, constraints, and dependencies
- \`mcp__signet__knowledge_expand_session\` — find session summaries linked to an entity (temporal drill-down)

About This System
---

When users ask about your memory or how you work across sessions:
Signet is a persistent identity and memory runtime. Your durable
substrate lives in \`AGENTS.md\`, \`SOUL.md\`, \`IDENTITY.md\`, and
\`USER.md\`. \`MEMORY.md\` is a rendered temporal head over deeper
working-memory state, not the canonical store. At prompt time, Signet
can surface context through hybrid retrieval across structured memory,
thread or temporal summaries, and transcript fallback when needed. Not
every important memory appears directly in \`MEMORY.md\`.

For the full pipeline details, read \`${root}/SIGNET-ARCHITECTURE.md\`.
${SIGNET_BLOCK_END}

`;
}

/**
 * Build the SIGNET-ARCHITECTURE.md content — an agent-facing explainer
 * of how the memory pipeline works. This file lives in the Signet workspace and
 * is referenced from the Signet block so agents can read it on demand.
 */
export function buildArchitectureDoc(workspace = "$SIGNET_WORKSPACE"): string {
	const root = normalizeWorkspace(workspace);
	return `# How Signet Works (for the agent reading this)

You are operating inside a system you cannot fully observe. The markdown
files in your context are prompt surfaces over deeper runtime state. Do
not make architectural claims based solely on what appears in your
context window — you are seeing rendered summaries and projections, not
the entire system.

## What happens on every session

### Session start
When your session begins, Signet fires a hook that:
1. Loads your identity files (AGENTS.md, SOUL.md, IDENTITY.md, USER.md)
2. Loads your rendered working-memory head (MEMORY.md)
3. Injects relevant context for continuity before generation starts
4. Preserves agent and session scoping on the state it loads

### Every user message
On each prompt from the user, Signet:
1. May retrieve context through hybrid recall before generation
2. Prefers structured distillation surfaces when available
3. Can also use thread heads and temporal summaries
4. Falls back to transcript retrieval when structured state has not
   caught up yet or transcript-specific lookup is needed

Prompt-time context is layered. \`MEMORY.md\` is only one visible surface.
Not every important state appears directly inside it.

### Session end
When the session closes, Signet:
1. Persists transcript and session state with agent and session scoping
2. Produces temporal artifacts such as summaries, and compaction artifacts
   when the harness supports them
3. Distills durable structure into deeper memory state
4. Refreshes rendered working-memory surfaces from that state

You never see this happen — it runs after you're gone.

## Your role in the memory system

Auto-capture handles most episodic and operational memory work. Your job
is to actively maintain the durable identity substrate:

- \`${root}/AGENTS.md\`
- \`${root}/SOUL.md\`
- \`${root}/IDENTITY.md\`
- \`${root}/USER.md\`

Update those files when you learn stable truths about how you operate,
who you are, who the user is, or how you should relate to the world.

Use \`signet remember\` (or \`/remember\`) for exceptionally important
things the system might otherwise underweight or miss. Use
\`signet recall\` (or \`/recall\`) when you need specific context that
was not automatically surfaced.

## Identity files are your durable substrate

You should maintain:

- \`${root}/AGENTS.md\`
- \`${root}/SOUL.md\`
- \`${root}/IDENTITY.md\`
- \`${root}/USER.md\`

Use them for durable truths about how you operate, who you are, who the
user is, and how you should relate to the world. Prefer additive,
intentional refinements over full rewrites unless the user asks for a
deeper identity change.

Do not edit \`${root}/MEMORY.md\` manually. It is a derived operational
summary and rendered temporal head regenerated by Signet from the memory
system.

## When users ask about your memory

You can explain truthfully:

"I have a persistent memory and identity system called Signet. It keeps
durable identity files, renders a working-memory head for continuity,
and can surface deeper context through hybrid retrieval across
structured memory, temporal summaries, and transcript fallback when
needed."

Do not speculate about implementation details beyond what's described
here. If pressed for specifics, suggest the user check the Signet
dashboard at http://localhost:3850.
`;
}

/**
 * Strip any existing Signet block from content to prevent duplication
 * when re-generating files.
 *
 * This handles the case where users' AGENTS.md was copied from a template
 * that already contains the Signet block, ensuring we don't create duplicates
 * on subsequent sync operations.
 */
export function stripSignetBlock(content: string): string {
	const pattern = new RegExp(
		`${escapeRegex(SIGNET_BLOCK_START)}[\\s\\S]*?${escapeRegex(SIGNET_BLOCK_END)}\\n?`,
		"g",
	);
	return content.replace(pattern, "");
}

/**
 * Check if content contains a Signet block
 */
export function hasSignetBlock(content: string): boolean {
	return content.includes(SIGNET_BLOCK_START);
}

/**
 * Extract the Signet block content (without delimiters) if present
 */
export function extractSignetBlock(content: string): string | null {
	const pattern = new RegExp(
		`${escapeRegex(SIGNET_BLOCK_START)}([\\s\\S]*?)${escapeRegex(SIGNET_BLOCK_END)}`,
	);
	const match = content.match(pattern);
	return match ? match[1].trim() : null;
}

// Helper to escape special regex characters
function escapeRegex(str: string): string {
	return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function normalizeWorkspace(workspace: string): string {
	// Strip markdown-significant characters that could break injected code spans
	// (backticks close code spans, newlines break inline structure)
	const root = workspace.trim().replace(/[`\n\r]/g, "");
	if (!root) {
		return "$SIGNET_WORKSPACE";
	}
	return root.endsWith("/") ? root.slice(0, -1) : root;
}
