export const DASHBOARD_LICENSES = [
	{
		name: "React",
		packages: "react · react-dom",
		license: "MIT",
		href: "https://github.com/facebook/react",
	},
	{
		name: "Radix UI",
		packages: "radix-ui · @radix-ui/react-slot",
		license: "MIT",
		href: "https://github.com/radix-ui/primitives",
	},
	{
		name: "shadcn/ui",
		packages: "@shadcn/react",
		license: "MIT",
		href: "https://github.com/shadcn-ui/ui",
	},
	{
		name: "Class Variance Authority",
		packages: "class-variance-authority",
		license: "Apache-2.0",
		href: "https://github.com/joe-bell/cva",
	},
	{
		name: "clsx",
		packages: "clsx",
		license: "MIT",
		href: "https://github.com/lukeed/clsx",
	},
	{
		name: "Lucide",
		packages: "lucide-react",
		license: "ISC",
		href: "https://github.com/lucide-icons/lucide",
	},
	{
		name: "next-themes",
		packages: "next-themes",
		license: "MIT",
		href: "https://github.com/pacocoursey/next-themes",
	},
	{
		name: "Sonner",
		packages: "sonner",
		license: "MIT",
		href: "https://github.com/emilkowalski/sonner",
	},
	{
		name: "Tailwind CSS",
		packages: "@tailwindcss/vite · tailwindcss",
		license: "MIT",
		href: "https://github.com/tailwindlabs/tailwindcss",
	},
	{
		name: "Tailwind Merge",
		packages: "tailwind-merge",
		license: "MIT",
		href: "https://github.com/dcastil/tailwind-merge",
	},
	{
		name: "Three.js",
		packages: "three",
		license: "MIT",
		href: "https://github.com/mrdoob/three.js",
	},
	{
		name: "YAML",
		packages: "yaml",
		license: "ISC",
		href: "https://github.com/eemeli/yaml",
	},
	{
		name: "DefinitelyTyped",
		packages: "@types/react · @types/react-dom · @types/three",
		license: "MIT",
		href: "https://github.com/DefinitelyTyped/DefinitelyTyped",
	},
	{
		name: "@types/yaml",
		packages: "@types/yaml",
		license: "MIT",
		href: "https://github.com/eemeli/yaml",
	},
	{
		name: "Vite",
		packages: "vite",
		license: "MIT",
		href: "https://github.com/vitejs/vite",
	},
	{
		name: "@vitejs/plugin-react",
		packages: "@vitejs/plugin-react",
		license: "MIT",
		href: "https://github.com/vitejs/vite-plugin-react",
	},
	{
		name: "Happy DOM",
		packages: "happy-dom",
		license: "MIT",
		href: "https://github.com/capricorn86/happy-dom",
	},
	{
		name: "tw-animate-css",
		packages: "tw-animate-css",
		license: "MIT",
		href: "https://github.com/Wombosvideo/tw-animate-css",
	},
	{
		name: "TypeScript",
		packages: "typescript",
		license: "Apache-2.0",
		href: "https://github.com/microsoft/TypeScript",
	},
	{
		name: "Geist",
		packages: "@fontsource/geist · @fontsource/geist-mono",
		license: "OFL-1.1",
		href: "https://github.com/fontsource/font-files",
	},
] as const;
