use crate::{execute, routes::auth, ApiError, AppState};
use axum::{extract::{Path, Query, State}, http::{HeaderMap, StatusCode}, routing::{get, post}, Json, Router};
use serde::Deserialize;
use serde_json::Value;
use std::{collections::HashMap, process::{Command, Stdio}, sync::{Mutex, OnceLock}, thread, time::{Duration, SystemTime, UNIX_EPOCH}};
use uuid::Uuid;

const MAX_QUEUE: usize = 32;
const MAX_OUTPUT: usize = 64 * 1024;
const RETENTION: Duration = Duration::from_secs(15 * 60);
const DEFAULT_TIMEOUT: u64 = 30_000;
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ExecBody { command: String, secrets: HashMap<String,String>, timeout_ms: Option<u64>, max_output_bytes: Option<usize> }
#[derive(Deserialize, Default)] struct ListQuery { limit: Option<usize> }
#[derive(Deserialize)] struct SecretBody { name: String, value: String }
static JOBS: OnceLock<Mutex<HashMap<String, Value>>> = OnceLock::new();
fn jobs() -> &'static Mutex<HashMap<String, Value>> { JOBS.get_or_init(|| Mutex::new(HashMap::new())) }
fn now() -> String {
    time::OffsetDateTime::now_utc().format(&time::format_description::well_known::Rfc3339).unwrap_or_else(|_| "1970-01-01T00:00:00Z".into())
}
fn bounded(v: &str, label: &str, max: usize) -> Result<String,ApiError> { if v.trim().is_empty() || v.len()>max { Err(ApiError::bad_request(format!("{label} must be 1-{max} UTF-8 bytes"))) } else { Ok(v.to_owned()) } }
fn header_alias(h: &HeaderMap, names: &[&str], label: &str) -> Result<Option<String>,ApiError> { let mut out=None; for n in names { for v in h.get_all(*n).iter() { let v=v.to_str().map_err(|_|ApiError::bad_request(format!("{label} header must be valid UTF-8")))?.trim(); if v.is_empty(){continue} if out.as_deref().is_some_and(|x|x!=v){return Err(ApiError::bad_request(format!("conflicting {label} aliases")))} out=Some(v.to_owned()); }} Ok(out) }
async fn authority(state:&AppState,h:&HeaderMap,cap:&str)->Result<(String,String),ApiError>{ let c=auth::gate(state,h).await?; if c.get("role").and_then(Value::as_str)!=Some("admin"){return Err(ApiError{status:StatusCode::FORBIDDEN,code:"forbidden",message:"admin authority is required".into()})} let p=c.get("permissions").and_then(Value::as_array).cloned().unwrap_or_default(); if !p.is_empty()&&!p.iter().any(|v|v.as_str()==Some(cap)){return Err(ApiError{status:StatusCode::FORBIDDEN,code:"forbidden",message:format!("{cap} capability is required")})} let a=header_alias(h,&["x-signet-agent-id","x-signet-agent"],"agent")?.or_else(||c.get("agentId").and_then(Value::as_str).map(str::to_owned)).ok_or_else(||ApiError::unauthorized("agent identity is required"))?; let w=header_alias(h,&["x-signet-workspace-id","x-signet-workspace","x-workspace-id"],"workspace")?.unwrap_or_else(||"default".into()); if let Some(s)=c.get("scope").and_then(Value::as_object){if s.get("agent").and_then(Value::as_str).is_some_and(|x|x!=a)||s.get("workspace").and_then(Value::as_str).is_some_and(|x|x!=w){return Err(ApiError{status:StatusCode::FORBIDDEN,code:"forbidden",message:"requested scope exceeds authenticated authority".into()})}} Ok((bounded(&a,"agent id",256)?,bounded(&w,"workspace id",256)?)) }
pub(crate) fn router()->Router<AppState>{Router::new().route("/api/secrets",get(list).post(upsert)).route("/api/secrets/{name}",post(upsert_named).delete(remove)).route("/api/secrets/exec",post(exec)).route("/api/secrets/exec/{job_id}",get(exec_status)).route("/api/secrets/{name}/exec",post(unsupported_exec)).route("/api/secrets/1password/{*rest}",get(unsupported_provider).post(unsupported_provider)).route("/api/secrets/bitwarden/{*rest}",get(unsupported_provider).post(unsupported_provider))}
async fn list(State(s):State<AppState>,h:HeaderMap,Query(q):Query<ListQuery>)->Result<Json<Value>,ApiError>{let(a,w)=authority(&s,&h,"secrets:list").await?;let l=q.limit.unwrap_or(100);if l==0||l>100{return Err(ApiError::bad_request("limit must be between 1 and 100"))}let r=execute(&s,signet_core_native::Operation::SecretList{agent_id:a,workspace_id:w,limit:l}).await?;Ok(Json(serde_json::json!({"secrets":r.get("items").cloned().unwrap_or(Value::Array(vec![])),"provider":"local"})))}
async fn upsert(State(s):State<AppState>,h:HeaderMap,Json(b):Json<SecretBody>)->Result<(StatusCode,Json<Value>),ApiError>{upsert_inner(s,h,b.name,b.value).await}
async fn upsert_named(State(s):State<AppState>,h:HeaderMap,Path(n):Path<String>,Json(b):Json<Value>)->Result<(StatusCode,Json<Value>),ApiError>{upsert_inner(s,h,n,b.get("value").and_then(Value::as_str).ok_or_else(||ApiError::bad_request("value is required"))?.into()).await}
async fn upsert_inner(s:AppState,h:HeaderMap,n:String,v:String)->Result<(StatusCode,Json<Value>),ApiError>{let(a,w)=authority(&s,&h,"secrets:write").await?;let n=bounded(&n,"secret name",256)?;let v=bounded(&v,"secret value",64*1024)?;execute(&s,signet_core_native::Operation::SecretUpsert{agent_id:a,workspace_id:w,name:n.clone(),value:v}).await?;Ok((StatusCode::CREATED,Json(serde_json::json!({"success":true,"name":n}))))}
async fn remove(State(s):State<AppState>,h:HeaderMap,Path(n):Path<String>)->Result<Json<Value>,ApiError>{let(a,w)=authority(&s,&h,"secrets:delete").await?;execute(&s,signet_core_native::Operation::SecretDelete{agent_id:a,workspace_id:w,name:bounded(&n,"secret name",256)?}).await?;Ok(Json(serde_json::json!({"success":true,"name":n})))}
fn argv(command:&str)->Result<Vec<String>,ApiError>{if command.trim().is_empty()||command.chars().any(|c|";|&`$(){}[]<>!\\\"'".contains(c)){return Err(ApiError::bad_request("command is invalid"))}let a=command.split_whitespace().map(str::to_owned).collect::<Vec<_>>();if a.is_empty(){Err(ApiError::bad_request("command is invalid"))}else{Ok(a)}}
fn redact(mut s:String, vals:&[String])->String{for v in vals{if !v.is_empty(){s=s.replace(v,"[REDACTED]")}}s}
fn run(argv:Vec<String>,env:HashMap<String,String>,timeout:u64,cap:usize)->Value{let mut c=Command::new(&argv[0]);c.args(&argv[1..]).envs(&env).stdout(Stdio::piped()).stderr(Stdio::piped());let Ok(mut child)=c.spawn()else{return serde_json::json!({"status":"failed","code":1,"stdout":"","stderr":"process failed","truncated":false})};let out=child.stdout.take().unwrap();let err=child.stderr.take().unwrap();let read=|mut r:Box<dyn std::io::Read+Send>|thread::spawn(move||{let mut b=Vec::new();r.read_to_end(&mut b).ok();b});let ro=read(Box::new(out));let re=read(Box::new(err));let start=std::time::Instant::now();let mut timed=false;let status=loop{if let Ok(Some(s))=child.try_wait(){break s.code().unwrap_or(1)}if start.elapsed()>=Duration::from_millis(timeout){let _=child.kill();timed=true;break 124}thread::sleep(Duration::from_millis(10))};let ob=ro.join().unwrap_or_default();let eb=re.join().unwrap_or_default();let trunc=ob.len()>cap||eb.len()>cap;let clip=|b:Vec<u8>|String::from_utf8_lossy(&b[..b.len().min(cap)]).into_owned();let vals=env.values().cloned().collect::<Vec<_>>();serde_json::json!({"status":if timed{"failed"}else if status==0{"completed"}else{"failed"},"code":status,"stdout":redact(clip(ob),&vals),"stderr":redact(clip(eb),&vals),"truncated":trunc,"timeout":timed})}
async fn exec(State(s):State<AppState>,h:HeaderMap,Json(b):Json<ExecBody>)->Result<(StatusCode,Json<Value>),ApiError>{let(a,w)=authority(&s,&h,"secrets:exec").await?;let av=argv(&b.command)?;if b.secrets.is_empty(){return Err(ApiError::bad_request("secrets must be a non-empty string map"))}let timeout=b.timeout_ms.unwrap_or(DEFAULT_TIMEOUT).clamp(1,120_000);let cap=b.max_output_bytes.unwrap_or(MAX_OUTPUT).clamp(1,MAX_OUTPUT);let id=Uuid::new_v4().to_string();let created=now();{let mut j=jobs().lock().unwrap();j.retain(|_,v|v.get("createdAt").and_then(Value::as_str).and_then(|x|x.parse::<u64>().ok()).map(|x|SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs().saturating_sub(x)<RETENTION.as_secs()).unwrap_or(true));if j.len()>=MAX_QUEUE{return Err(ApiError{status:StatusCode::TOO_MANY_REQUESTS,code:"queue_full",message:"execution queue is full".into()})}j.insert(id.clone(),serde_json::json!({"id":id,"status":"queued","createdAt":created,"startedAt":Value::Null,"completedAt":Value::Null,"timeoutMs":timeout,"result":Value::Null,"error":Value::Null}));}let refs=b.secrets;let s2=s.clone();let jid=id.clone();let created2=created.clone();tokio::spawn(async move{let mut env=HashMap::new();for(k,n)in refs{if let Ok(v)=execute(&s2,signet_core_native::Operation::SecretGet{agent_id:a.clone(),workspace_id:w.clone(),name:n}).await{if let Some(x)=v.get("value").and_then(Value::as_str){env.insert(k,x.to_owned());}}}let r=tokio::task::spawn_blocking(move||run(av,env,timeout,cap)).await.unwrap();let mut x=jobs().lock().unwrap();if x.contains_key(&jid){x.insert(jid.clone(),serde_json::json!({"id":jid,"status":r.get("status").cloned().unwrap_or(Value::String("failed".into())),"createdAt":created2,"timeoutMs":timeout,"completedAt":now(),"result":r}));}});Ok((StatusCode::ACCEPTED,Json(serde_json::json!({"id":id,"status":"queued","createdAt":created,"timeoutMs":timeout}))))}
async fn exec_status(State(s):State<AppState>,h:HeaderMap,Path(id):Path<String>)->Result<Json<Value>,ApiError>{let _=authority(&s,&h,"secrets:exec").await?;jobs().lock().unwrap().get(&id).cloned().map(Json).ok_or_else(||ApiError::not_found("job not found"))}
async fn unsupported_exec(State(s):State<AppState>,h:HeaderMap)->Result<Json<Value>,ApiError>{let _=authority(&s,&h,"secrets:exec").await?;Err(ApiError{status:StatusCode::NOT_IMPLEMENTED,code:"unsupported",message:"secret execution is unsupported".into()})}
async fn unsupported_provider(State(s):State<AppState>,h:HeaderMap)->Result<Json<Value>,ApiError>{let _=authority(&s,&h,"secrets:providers:list").await?;Err(ApiError{status:StatusCode::NOT_IMPLEMENTED,code:"unsupported",message:"external secret providers are unsupported".into()})}
