import { expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
	analyzeSourceTree,
	canonicalizeBaselineInventory,
	compareArchitectureRatchet,
	loadBaseline,
	renderReport,
} from "./audit-architecture-contract";

test("the committed baseline reproduces the current source and package inventory", () => {
	const baseline = loadBaseline();
	const current = analyzeSourceTree();
	expect(canonicalizeBaselineInventory(current)).toEqual(baseline);
	expect(current.summary.runtimeCycles).toBe(0);
	expect(current.summary.computedLoads).toBe(2);
	expect(current.summary.unresolvedEdges).toBeGreaterThanOrEqual(0);
	expect(current.generatedArtifacts.length).toBeGreaterThan(0);
	expect(current.generatedArtifactManifest).toHaveLength(4);
	expect(current.summary.packages).toBe(34);
});

test("the pull-request workflow runs the canonical blocking audit", () => {
	const workflow = readFileSync(join(import.meta.dir, "../.github/workflows/architecture-ratchet.yml"), "utf8");
	expect(workflow).toContain("on:\n  pull_request:");
	expect(workflow).toContain("run: bun test scripts/audit-architecture-contract.test.ts");
	expect(workflow).toContain("run: bun run audit:architecture");
});

test("structural edge identities survive unrelated line insertion", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-contract-"));
	try {
		writeFileSync(join(root, "types.ts"), "export interface Item { value: string; }\n");
		writeFileSync(
			join(root, "consumer.ts"),
			'import type { Item } from "./types";\nexport const value: Item = { value: "ok" };\n',
		);
		const first = analyzeSourceTree({ root, sourceRoot: root });
		writeFileSync(
			join(root, "consumer.ts"),
			'\n// unrelated lines must not churn structural identities\nimport type { Item } from "./types";\nexport const value: Item = { value: "ok" };\n',
		);
		const second = analyzeSourceTree({ root, sourceRoot: root });
		expect(second.sourceFiles.map((file) => file.id)).toEqual(first.sourceFiles.map((file) => file.id));
		expect(second.sourceEdges.map((edge) => edge.id)).toEqual(first.sourceEdges.map((edge) => edge.id));
		expect(second.typeCycles).toEqual(first.typeCycles);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("the source graph separates type-only cycles from runtime cycles", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-cycle-"));
	try {
		writeFileSync(join(root, "a.ts"), 'export { type B } from "./b";\n');
		writeFileSync(join(root, "b.ts"), 'export { type A } from "./a";\n');
		const inventory = analyzeSourceTree({ root, sourceRoot: root });
		expect(inventory.summary.runtimeCycles).toBe(0);
		expect(inventory.summary.typeCycles).toBe(1);
		expect(inventory.typeCycles[0]?.nodes).toEqual(["a.ts", "b.ts"]);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("manifested outputs are measured and excluded from handwritten source files", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-artifacts-"));
	try {
		writeFileSync(join(root, "package.json"), JSON.stringify({ name: "fixture-root" }));
		const normalOutput =
			"// Auto-generated by scripts/generate.ts\n// Architecture provenance: generatedBy=scripts/generate.ts\nexport const generated = true;\n";
		const bundleOutput =
			"// Auto-generated by scripts/generate.ts\n// Architecture provenance: generatedBy=scripts/generate.ts\nexport const bundled = true;\n";
		writeFileSync(join(root, "normal-output.ts"), normalOutput);
		writeFileSync(join(root, "handwritten.ts"), "export const handwritten = true;\n");
		mkdirSync(join(root, "src"));
		writeFileSync(join(root, "src", "fixture-bundle.ts"), bundleOutput);
		mkdirSync(join(root, "scripts"));
		writeFileSync(
			join(root, "scripts", "generate.ts"),
			'import { join } from "node:path";\nimport { writeFileSync } from "node:fs";\n// Architecture provenance: source=src\n// src outputs missing-output.ts, normal-output.ts, and fixture-bundle.ts\nconst normal = join(__dirname, "..", "normal-output.ts");\nconst bundle = join(__dirname, "..", "src", "fixture-bundle.ts");\nconst missing = join(__dirname, "..", "missing-output.ts");\nwriteFileSync(normal, "");\nwriteFileSync(bundle, "");\nwriteFileSync(missing, "");\n',
		);
		writeFileSync(
			join(root, "scripts", "architecture-generated-artifacts.json"),
			JSON.stringify({
				version: 1,
				artifacts: [
					{
						path: "missing-output.ts",
						owner: "fixture-root",
						source: "src",
						generatedBy: "scripts/generate.ts",
					},
					{
						path: "normal-output.ts",
						owner: "fixture-root",
						source: "src",
						generatedBy: "scripts/generate.ts",
					},
					{
						path: "src/fixture-bundle.ts",
						owner: "fixture-root",
						source: "src",
						generatedBy: "scripts/generate.ts",
					},
				],
			}),
		);
		const inventory = analyzeSourceTree({ root, sourceRoot: root });
		expect(inventory.generatedArtifacts).toContainEqual({
			path: "normal-output.ts",
			lines: normalOutput.split("\n").length,
			bytes: Buffer.byteLength(normalOutput),
			materialized: true,
			reason: "manifested-output",
		});
		expect(inventory.generatedArtifacts).toContainEqual(
			expect.objectContaining({
				path: "src/fixture-bundle.ts",
				lines: bundleOutput.split("\n").length,
				bytes: Buffer.byteLength(bundleOutput),
				materialized: true,
				reason: "manifested-output",
			}),
		);
		expect(inventory.sourceFiles.map((file) => file.path)).toEqual(["handwritten.ts", "scripts/generate.ts"]);
		expect(renderReport(inventory)).toContain("`missing-output.ts`");
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("manifest provenance rejects a handwritten file hidden by a fake entry", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-manifest-"));
	try {
		writeFileSync(join(root, "package.json"), JSON.stringify({ name: "fixture-root" }));
		writeFileSync(join(root, "handwritten.ts"), "export const handwritten = true;\n");
		mkdirSync(join(root, "src"));
		mkdirSync(join(root, "scripts"));
		writeFileSync(
			join(root, "scripts", "generate.ts"),
			'import { join } from "node:path";\nimport { writeFileSync } from "node:fs";\n// Architecture provenance: source=src\n// src produces handwritten.ts\nconst output = join(__dirname, "..", "handwritten.ts");\nwriteFileSync(output, "");\n',
		);
		writeFileSync(
			join(root, "scripts", "architecture-generated-artifacts.json"),
			JSON.stringify({
				version: 1,
				artifacts: [
					{
						path: "handwritten.ts",
						owner: "fixture-root",
						source: "src",
						generatedBy: "scripts/generate.ts",
					},
				],
			}),
		);
		expect(() => analyzeSourceTree({ root, sourceRoot: root })).toThrow("without a provenance header");
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("unmanifested generated markers, paths, and bundle names cannot hide source", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-unmanifested-"));
	try {
		writeFileSync(join(root, "package.json"), JSON.stringify({ name: "fixture-root" }));
		writeFileSync(join(root, "rogue.ts"), "// Auto-generated by scripts/unknown.ts\nexport const rogue = true;\n");
		mkdirSync(join(root, "generated"));
		writeFileSync(join(root, "generated", "path-rogue.ts"), "export const rogue = true;\n");
		mkdirSync(join(root, "src"));
		writeFileSync(join(root, "src", "name-bundle.ts"), "export const rogue = true;\n");
		expect(() => analyzeSourceTree({ root, sourceRoot: root })).toThrow(
			"not listed in scripts/architecture-generated-artifacts.json",
		);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("optional workspace dependencies are included in runtime and all package graphs", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-packages-"));
	try {
		writeFileSync(
			join(root, "package.json"),
			JSON.stringify({ name: "fixture-root", optionalDependencies: { "fixture-child": "workspace:*" } }),
		);
		mkdirSync(join(root, "packages", "child"), { recursive: true });
		writeFileSync(join(root, "packages", "child", "package.json"), JSON.stringify({ name: "fixture-child" }));
		const inventory = analyzeSourceTree({ root, sourceRoot: root });
		expect(inventory.packages.find((item) => item.name === "fixture-root")?.optionalDependencies).toEqual([
			"fixture-child",
		]);
		expect(inventory.packageRuntimeEdges).toContainEqual({ from: "", to: "packages/child" });
		expect(inventory.packageAllEdges).toContainEqual({ from: "", to: "packages/child" });
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("literal dynamic loads enter the graph and computed loads enter the ledger", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-loads-"));
	try {
		writeFileSync(join(root, "target.ts"), "export const target = true;\n");
		writeFileSync(
			join(root, "loader.ts"),
			[
				'void import("./target.js");',
				'const moduleName = "./target";',
				"void require(moduleName);",
				"void import(runtimePath);",
			].join("\n"),
		);
		const inventory = analyzeSourceTree({ root, sourceRoot: root });
		expect(inventory.sourceEdges.filter((edge) => edge.kind === "dynamic-import")).toHaveLength(1);
		expect(inventory.sourceEdges.filter((edge) => edge.kind === "require")).toHaveLength(1);
		expect(inventory.computedLoads).toHaveLength(1);
		expect(inventory.computedLoads[0]?.kind).toBe("dynamic-import");
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("manifested build materialization does not churn the canonical baseline", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-materialization-"));
	try {
		writeFileSync(join(root, "package.json"), JSON.stringify({ name: "fixture-root" }));
		mkdirSync(join(root, "source"));
		mkdirSync(join(root, "scripts"));
		writeFileSync(join(root, "source", "entry.ts"), "export const entry = true;\n");
		writeFileSync(
			join(root, "scripts", "generate.ts"),
			'import { join } from "node:path";\nimport { writeFileSync } from "node:fs";\n// Architecture provenance: source=source\n// source outputs generated.ts\nwriteFileSync(join(__dirname, "..", "generated.ts"), "");\n',
		);
		writeFileSync(
			join(root, "scripts", "architecture-generated-artifacts.json"),
			JSON.stringify({
				version: 1,
				artifacts: [
					{
						path: "generated.ts",
						owner: "fixture-root",
						source: "source",
						generatedBy: "scripts/generate.ts",
					},
				],
			}),
		);
		const beforeBuild = analyzeSourceTree({ root, sourceRoot: root });
		const generatedOutput =
			"// Auto-generated by scripts/generate.ts\n// Architecture provenance: generatedBy=scripts/generate.ts\nexport const generated = true;\n";
		writeFileSync(join(root, "generated.ts"), generatedOutput);
		const afterBuild = analyzeSourceTree({ root, sourceRoot: root });
		expect(canonicalizeBaselineInventory(afterBuild)).toEqual(canonicalizeBaselineInventory(beforeBuild));
		expect(afterBuild.generatedArtifacts).toContainEqual({
			path: "generated.ts",
			lines: generatedOutput.split("\n").length,
			bytes: Buffer.byteLength(generatedOutput),
			materialized: true,
			reason: "manifested-output",
		});
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("shadowed bindings keep computed runtime loads in the ledger", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-scope-"));
	try {
		writeFileSync(join(root, "target.ts"), "export const target = true;\n");
		writeFileSync(
			join(root, "loader.ts"),
			[
				'const path = "./target";',
				"export function load(path: string) { return import(path); }",
				'export function literal() { const path = "./target"; return require(path); }',
			].join("\n"),
		);
		const inventory = analyzeSourceTree({ root, sourceRoot: root });
		expect(inventory.computedLoads).toHaveLength(1);
		expect(inventory.computedLoads[0]?.kind).toBe("dynamic-import");
		expect(inventory.sourceEdges).toContainEqual(
			expect.objectContaining({ kind: "require", specifier: "./target", to: "target.ts", runtime: true }),
		);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("shadowed require bindings do not fabricate runtime edges or cycles", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-require-shadow-"));
	try {
		writeFileSync(join(root, "target.ts"), "export const target = true;\n");
		writeFileSync(
			join(root, "loader.ts"),
			['import "./target";', "const require = (_path: string) => undefined;", 'require("./target");'].join("\n"),
		);
		const inventory = analyzeSourceTree({ root, sourceRoot: root });
		expect(inventory.sourceEdges.filter((edge) => edge.kind === "require")).toHaveLength(0);
		expect(inventory.computedLoads).toContainEqual(expect.objectContaining({ kind: "require", path: "loader.ts" }));
		expect(inventory.summary.runtimeCycles).toBe(0);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("nested-block var shadowing keeps computed runtime loads in the ledger", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-var-scope-"));
	try {
		writeFileSync(join(root, "target.ts"), "export const target = true;\n");
		writeFileSync(
			join(root, "loader.ts"),
			[
				'const path = "./target";',
				"export function load(runtimePath: string) {",
				"	return import(path);",
				"	if (globalThis) { var path = runtimePath; }",
				"}",
			].join("\n"),
		);
		const inventory = analyzeSourceTree({ root, sourceRoot: root });
		expect(inventory.computedLoads).toHaveLength(1);
		expect(inventory.computedLoads[0]?.kind).toBe("dynamic-import");
		expect(inventory.sourceEdges).not.toContainEqual(
			expect.objectContaining({ kind: "dynamic-import", specifier: "./target", to: "target.ts", runtime: true }),
		);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("loop bindings do not leak into the enclosing scope after the loop", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-loop-scope-"));
	try {
		writeFileSync(join(root, "target.ts"), "export const target = true;\n");
		writeFileSync(
			join(root, "loader.ts"),
			[
				'const path = "./target";',
				'export function loadFor() { for (const path = "./other"; false; ) {} return import(path); }',
				"export function loadForIn() { for (const path in { other: true }) {} return import(path); }",
				'export function loadForOf() { for (const path of ["./other"]) {} return import(path); }',
			].join("\n"),
		);
		const inventory = analyzeSourceTree({ root, sourceRoot: root });
		expect(inventory.computedLoads).toHaveLength(0);
		expect(inventory.sourceEdges.filter((edge) => edge.kind === "dynamic-import")).toHaveLength(3);
		expect(inventory.sourceEdges).toEqual(
			expect.arrayContaining([
				expect.objectContaining({ kind: "dynamic-import", specifier: "./target", to: "target.ts", runtime: true }),
			]),
		);
		expect(inventory.sourceEdges).not.toContainEqual(
			expect.objectContaining({ kind: "dynamic-import", specifier: "./other", runtime: true }),
		);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("ratchet rejects module, public-surface, and type-escape growth", () => {
	const baseline = loadBaseline();
	const first = baseline.sourceFiles[0];
	expect(first).toBeDefined();
	if (first === undefined) return;
	const current = {
		...baseline,
		sourceFiles: baseline.sourceFiles.map((module) =>
			module.path === first.path
				? {
						...module,
						logicalStatements: module.logicalStatements + 1,
						exports: module.exports + 1,
						typeEscapes: (module.typeEscapes ?? 0) + 1,
					}
				: module,
		),
	};
	const findings = compareArchitectureRatchet(current, baseline);
	expect(findings).toEqual(
		expect.arrayContaining([
			expect.stringContaining(`module growth in ${first.path}`),
			expect.stringContaining(`public-surface growth in ${first.path}`),
			expect.stringContaining(`type-escape growth in ${first.path}`),
		]),
	);
});

test("ratchet rejects runtime cycles and expanded type SCCs", () => {
	const baseline = loadBaseline();
	const existing = baseline.typeCycles[0];
	expect(existing).toBeDefined();
	if (existing === undefined) return;
	const current = {
		...baseline,
		runtimeCycles: [{ id: "runtime-cycle", nodes: ["a.ts", "b.ts"] }],
		summary: { ...baseline.summary, runtimeCycles: 1 },
		typeCycles: [{ id: "expanded-cycle", nodes: [...existing.nodes, "new.ts"] }],
	};
	const findings = compareArchitectureRatchet(current, baseline);
	expect(findings).toEqual(
		expect.arrayContaining([
			expect.stringContaining("runtime source cycles exceed the zero budget"),
			expect.stringContaining("new or expanded type-inclusive SCC expanded-cycle"),
		]),
	);
});

test("ratchet rejects new forbidden layer edges and routes/state importers", () => {
	const baseline = loadBaseline();
	const current = {
		...baseline,
		sourceEdges: [
			...baseline.sourceEdges,
			{
				id: "synthetic-boundary-edge",
				from: "platform/core/src/package-manager.ts",
				to: "platform/daemon/src/routes/state.ts",
				specifier: "./state",
				kind: "import" as const,
				runtime: true,
				line: 1,
			},
		],
	};
	const findings = compareArchitectureRatchet(current, baseline);
	expect(findings).toEqual(
		expect.arrayContaining([
			expect.stringContaining("new forbidden source-layer edge"),
			expect.stringContaining("new routes/state.ts importer platform/core/src/package-manager.ts"),
		]),
	);
});

test("configured tsconfig path aliases participate in runtime SCC detection", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-alias-cycle-"));
	try {
		writeFileSync(
			join(root, "tsconfig.json"),
			JSON.stringify({ compilerOptions: { baseUrl: ".", paths: { "@/*": ["./*"] } } }),
		);
		writeFileSync(join(root, "a.ts"), 'import { b } from "@/b";\nexport const a = b;\n');
		writeFileSync(join(root, "b.ts"), 'import { a } from "@/a";\nexport const b = a;\n');
		const inventory = analyzeSourceTree({ root, sourceRoot: root });
		expect(inventory.sourceEdges.filter((edge) => edge.to !== null)).toHaveLength(2);
		expect(inventory.summary.runtimeCycles).toBe(1);
		expect(inventory.sourceEdges.filter((edge) => edge.to === null)).toHaveLength(0);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("ImportEquals bindings prevent local require calls from becoming runtime edges", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-import-equals-"));
	try {
		writeFileSync(join(root, "fake.ts"), "export const fake = true;\n");
		writeFileSync(join(root, "target.ts"), "export const target = true;\n");
		writeFileSync(join(root, "loader.ts"), 'import require = require("./fake");\nrequire("./target");\n');
		const inventory = analyzeSourceTree({ root, sourceRoot: root });
		expect(inventory.sourceEdges.filter((edge) => edge.kind === "require")).toHaveLength(0);
		expect(inventory.computedLoads).toContainEqual(expect.objectContaining({ kind: "require", path: "loader.ts" }));
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("only the lexical canonical createRequire binding enables runtime require edges", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-create-require-"));
	try {
		writeFileSync(join(root, "target.ts"), "export const target = true;\n");
		writeFileSync(
			join(root, "loader.ts"),
			[
				'import { createRequire as canonical } from "node:module";',
				"function createRequire(_url: unknown) { return (_path: string) => undefined; }",
				"const require = createRequire(import.meta.url);",
				'require("./target");',
			].join("\n"),
		);
		const inventory = analyzeSourceTree({ root, sourceRoot: root });
		expect(inventory.sourceEdges.filter((edge) => edge.kind === "require")).toHaveLength(0);
		expect(inventory.computedLoads).toContainEqual(expect.objectContaining({ kind: "require", path: "loader.ts" }));
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("lexical fake createRequire bindings stay computed even with an unaliased canonical import", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-create-require-shadow-"));
	try {
		writeFileSync(join(root, "target.ts"), "export const target = true;\n");
		writeFileSync(
			join(root, "loader.ts"),
			[
				'import { createRequire } from "node:module";',
				"function load() {",
				"	const require = createRequire(import.meta.url);",
				'	require("./target");',
				"	function createRequire(_url: unknown) { return (_path: string) => undefined; }",
				"}",
			].join("\n"),
		);
		const inventory = analyzeSourceTree({ root, sourceRoot: root });
		expect(inventory.sourceEdges.filter((edge) => edge.kind === "require")).toHaveLength(0);
		expect(inventory.computedLoads).toContainEqual(expect.objectContaining({ kind: "require", path: "loader.ts" }));
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("outer canonical createRequire provenance survives an inner shadow", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-create-require-outer-scope-"));
	try {
		writeFileSync(join(root, "target.ts"), "export const target = true;\n");
		writeFileSync(
			join(root, "loader.ts"),
			[
				'import { createRequire } from "node:module";',
				"const require = createRequire(import.meta.url);",
				"function load() {",
				"function createRequire(_url: unknown) { return (_path: string) => undefined; }",
				'return require("./target");',
				"}",
			].join("\n"),
		);
		const inventory = analyzeSourceTree({ root, sourceRoot: root });
		expect(inventory.sourceEdges).toContainEqual(
			expect.objectContaining({ kind: "require", specifier: "./target", to: "target.ts", runtime: true }),
		);
		expect(inventory.computedLoads).not.toContainEqual(expect.objectContaining({ kind: "require", path: "loader.ts" }));
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("named export-list growth trips the public-surface ratchet", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-export-list-"));
	try {
		writeFileSync(join(root, "target.ts"), "export const one = true;\nexport const two = true;\n");
		writeFileSync(join(root, "consumer.ts"), 'export { one } from "./target";\n');
		const baseline = analyzeSourceTree({ root, sourceRoot: root });
		writeFileSync(join(root, "consumer.ts"), 'export { one, two } from "./target";\n');
		const current = analyzeSourceTree({ root, sourceRoot: root });
		expect(current.sourceFiles.find((file) => file.path === "consumer.ts")?.exports).toBe(2);
		expect(compareArchitectureRatchet(current, baseline)).toContain(
			"public-surface growth in consumer.ts: 1 -> 2 exports",
		);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("manifest output paths resolve identifiers in their lexical defining scope", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-manifest-output-scope-"));
	try {
		writeFileSync(join(root, "package.json"), JSON.stringify({ name: "fixture-root" }));
		mkdirSync(join(root, "src"));
		mkdirSync(join(root, "scripts"));
		writeFileSync(
			join(root, "scripts", "generate.ts"),
			[
				'import { writeFileSync } from "node:fs";',
				'import { join } from "node:path";',
				'const output = join(__dirname, "real.ts");',
				"function later() {",
				'\tconst output = join(__dirname, "fake.ts");',
				"}",
				"// Architecture provenance: source=src",
				"// src output",
				'writeFileSync(output, "");',
			].join("\n"),
		);
		writeFileSync(
			join(root, "scripts", "architecture-generated-artifacts.json"),
			JSON.stringify({
				version: 1,
				artifacts: [
					{
						path: "scripts/fake.ts",
						owner: "fixture-root",
						source: "src",
						generatedBy: "scripts/generate.ts",
					},
				],
			}),
		);
		expect(() => analyzeSourceTree({ root, sourceRoot: root })).toThrow(
			"does not write its exact output scripts/fake.ts",
		);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("manifest output paths reject mutable or reassigned bindings", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-manifest-output-mutable-"));
	try {
		writeFileSync(join(root, "package.json"), JSON.stringify({ name: "fixture-root" }));
		mkdirSync(join(root, "src"));
		mkdirSync(join(root, "scripts"));
		writeFileSync(
			join(root, "scripts", "generate.ts"),
			[
				'import { writeFileSync } from "node:fs";',
				'import { join } from "node:path";',
				'let output = join(__dirname, "real.ts");',
				'output = join(__dirname, "fake.ts");',
				"// Architecture provenance: source=src",
				"// src output",
				'writeFileSync(output, "");',
			].join("\n"),
		);
		writeFileSync(
			join(root, "scripts", "architecture-generated-artifacts.json"),
			JSON.stringify({
				version: 1,
				artifacts: [
					{
						path: "scripts/fake.ts",
						owner: "fixture-root",
						source: "src",
						generatedBy: "scripts/generate.ts",
					},
				],
			}),
		);
		expect(() => analyzeSourceTree({ root, sourceRoot: root })).toThrow(
			"Generated artifact generator has no statically verifiable output path",
		);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("manifest output paths require canonical path helper provenance", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-manifest-path-helper-"));
	try {
		writeFileSync(join(root, "package.json"), JSON.stringify({ name: "fixture-root" }));
		mkdirSync(join(root, "src"));
		mkdirSync(join(root, "scripts"));
		writeFileSync(
			join(root, "scripts", "generate.ts"),
			[
				'import { writeFileSync } from "node:fs";',
				'const join = (_dir: string, _name: string) => "/outside/actual.ts";',
				"// Architecture provenance: source=src",
				"// src output",
				'writeFileSync(join(__dirname, "output.ts"), "");',
			].join("\n"),
		);
		writeFileSync(
			join(root, "scripts", "architecture-generated-artifacts.json"),
			JSON.stringify({
				version: 1,
				artifacts: [
					{
						path: "scripts/output.ts",
						owner: "fixture-root",
						source: "src",
						generatedBy: "scripts/generate.ts",
					},
				],
			}),
		);
		expect(() => analyzeSourceTree({ root, sourceRoot: root })).toThrow(
			"Generated artifact generator has no statically verifiable output path",
		);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("manifest output paths require a canonical writeFileSync binding", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-manifest-writer-provenance-"));
	try {
		writeFileSync(join(root, "package.json"), JSON.stringify({ name: "fixture-root" }));
		mkdirSync(join(root, "src"));
		mkdirSync(join(root, "scripts"));
		writeFileSync(
			join(root, "scripts", "generate.ts"),
			[
				'import { writeFileSync as realWriteFileSync } from "node:fs";',
				'import { join } from "node:path";',
				"// generates files under src",
				"{",
				"const writeFileSync = (_path: string, _content: string) => undefined;",
				'writeFileSync(join(__dirname, "fake.ts"), "");',
				"}",
				'realWriteFileSync(join(__dirname, "actual.ts"), "");',
			].join("\n"),
		);
		writeFileSync(
			join(root, "scripts", "architecture-generated-artifacts.json"),
			JSON.stringify({
				version: 1,
				artifacts: [
					{
						path: "scripts/fake.ts",
						owner: "fixture-root",
						source: "src",
						generatedBy: "scripts/generate.ts",
					},
				],
			}),
		);
		expect(() => analyzeSourceTree({ root, sourceRoot: root })).toThrow(
			"does not write its exact output scripts/fake.ts",
		);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("non-wildcard path aliases do not match longer specifiers", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-exact-alias-"));
	try {
		writeFileSync(
			join(root, "tsconfig.json"),
			JSON.stringify({ compilerOptions: { baseUrl: ".", paths: { "@core": ["./core"] } } }),
		);
		writeFileSync(join(root, "core.ts"), 'import { value } from "./consumer";\nexport const core = value;\n');
		writeFileSync(join(root, "consumer.ts"), 'import { core } from "@core-extra";\nexport const value = core;\n');
		const inventory = analyzeSourceTree({ root, sourceRoot: root });
		expect(inventory.summary.runtimeCycles).toBe(0);
		expect(inventory.sourceEdges).toContainEqual(
			expect.objectContaining({ from: "consumer.ts", specifier: "@core-extra", to: null }),
		);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("manifest output paths must match the generator's resolved write target", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-manifest-output-"));
	try {
		writeFileSync(join(root, "package.json"), JSON.stringify({ name: "@signet/sdk" }));
		mkdirSync(join(root, "platform", "daemon", "src"), { recursive: true });
		mkdirSync(join(root, "libs", "sdk", "scripts"), { recursive: true });
		mkdirSync(join(root, "libs", "sdk", "src", "generated"), { recursive: true });
		writeFileSync(join(root, "platform", "daemon", "src", "daemon.ts"), "export const daemon = true;\n");
		writeFileSync(
			join(root, "libs", "sdk", "scripts", "generate-client.ts"),
			'import { join } from "node:path";\nimport { writeFileSync } from "node:fs";\n// Architecture provenance: source=platform/daemon/src/daemon.ts\n// generated from daemon.ts\nwriteFileSync(join(__dirname, "..", "src", "generated", "client.ts"), "");\n',
		);
		writeFileSync(
			join(root, "client.ts"),
			"/**\n * AUTO-GENERATED FILE — DO NOT EDIT\n * Generated by generate-client.ts\n */\nexport const hidden = true;\n",
		);
		mkdirSync(join(root, "scripts"));
		writeFileSync(
			join(root, "scripts", "architecture-generated-artifacts.json"),
			JSON.stringify({
				version: 1,
				artifacts: [
					{
						path: "client.ts",
						owner: "@signet/sdk",
						source: "platform/daemon/src/daemon.ts",
						generatedBy: "libs/sdk/scripts/generate-client.ts",
					},
				],
			}),
		);
		expect(() => analyzeSourceTree({ root, sourceRoot: root })).toThrow("does not write its exact output client.ts");
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("manifest output paths resolve new URL targets exactly", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-manifest-url-output-"));
	try {
		writeFileSync(join(root, "package.json"), JSON.stringify({ name: "fixture-root" }));
		mkdirSync(join(root, "src"));
		mkdirSync(join(root, "scripts", "fake-dir"), { recursive: true });
		writeFileSync(join(root, "src", "real-source.ts"), "export const source = true;\n");
		writeFileSync(
			join(root, "scripts", "generate.ts"),
			[
				'import { writeFileSync } from "node:fs";',
				'import { join } from "node:path";',
				'import { fileURLToPath } from "node:url";',
				"// Architecture provenance: source=src/real-source.ts",
				'const output = join(fileURLToPath(new URL("./fake-dir", import.meta.url)), "child.ts");',
				'writeFileSync(output, "");',
			].join("\n"),
		);
		writeFileSync(
			join(root, "scripts", "architecture-generated-artifacts.json"),
			JSON.stringify({
				version: 1,
				artifacts: [
					{
						path: "scripts/fake-dir/child.ts",
						owner: "fixture-root",
						source: "src/real-source.ts",
						generatedBy: "scripts/generate.ts",
					},
				],
			}),
		);
		expect(() => analyzeSourceTree({ root, sourceRoot: root })).not.toThrow();
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("namespace-local manifest bindings do not shadow an outer write", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-manifest-namespace-scope-"));
	try {
		writeFileSync(join(root, "package.json"), JSON.stringify({ name: "fixture-root" }));
		mkdirSync(join(root, "src"));
		mkdirSync(join(root, "scripts"));
		writeFileSync(join(root, "src", "real-source.ts"), "export const source = true;\n");
		writeFileSync(
			join(root, "scripts", "generate.ts"),
			[
				'import { writeFileSync } from "node:fs";',
				'import { join } from "node:path";',
				"// Architecture provenance: source=src/real-source.ts",
				'const output = join(__dirname, "real.ts");',
				"namespace Hidden {",
				'	const output = join(__dirname, "fake.ts");',
				"}",
				'writeFileSync(output, "");',
			].join("\n"),
		);
		writeFileSync(
			join(root, "scripts", "architecture-generated-artifacts.json"),
			JSON.stringify({
				version: 1,
				artifacts: [
					{
						path: "scripts/fake.ts",
						owner: "fixture-root",
						source: "src/real-source.ts",
						generatedBy: "scripts/generate.ts",
					},
				],
			}),
		);
		expect(() => analyzeSourceTree({ root, sourceRoot: root })).toThrow(
			"does not write its exact output scripts/fake.ts",
		);
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("materialized provenance rejects near-name generator headers", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-manifest-header-spoof-"));
	try {
		writeFileSync(join(root, "package.json"), JSON.stringify({ name: "fixture-root" }));
		mkdirSync(join(root, "src"));
		mkdirSync(join(root, "scripts"));
		writeFileSync(join(root, "src", "real-source.ts"), "export const source = true;\n");
		writeFileSync(
			join(root, "scripts", "generate.ts"),
			[
				'import { writeFileSync } from "node:fs";',
				'import { join } from "node:path";',
				"// Architecture provenance: source=src/real-source.ts",
				'writeFileSync(join(__dirname, "..", "output.ts"), "");',
			].join("\n"),
		);
		writeFileSync(join(root, "output.ts"), "// Auto-generated by not-generate.ts\nexport const output = true;\n");
		writeFileSync(
			join(root, "scripts", "architecture-generated-artifacts.json"),
			JSON.stringify({
				version: 1,
				artifacts: [
					{
						path: "output.ts",
						owner: "fixture-root",
						source: "src/real-source.ts",
						generatedBy: "scripts/generate.ts",
					},
				],
			}),
		);
		expect(() => analyzeSourceTree({ root, sourceRoot: root })).toThrow("without a provenance header");
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});

test("generator provenance rejects comment-only source-name spoofing", () => {
	const root = mkdtempSync(join(tmpdir(), "architecture-manifest-source-spoof-"));
	try {
		writeFileSync(join(root, "package.json"), JSON.stringify({ name: "fixture-root" }));
		mkdirSync(join(root, "src"));
		mkdirSync(join(root, "scripts"));
		writeFileSync(join(root, "src", "real-source.ts"), "export const source = true;\n");
		writeFileSync(
			join(root, "scripts", "generate.ts"),
			[
				'import { writeFileSync } from "node:fs";',
				'import { join } from "node:path";',
				"// generated from real-source.ts (comment only; source is never read)",
				'writeFileSync(join(__dirname, "..", "output.ts"), "");',
			].join("\n"),
		);
		writeFileSync(
			join(root, "scripts", "architecture-generated-artifacts.json"),
			JSON.stringify({
				version: 1,
				artifacts: [
					{
						path: "output.ts",
						owner: "fixture-root",
						source: "src/real-source.ts",
						generatedBy: "scripts/generate.ts",
					},
				],
			}),
		);
		expect(() => analyzeSourceTree({ root, sourceRoot: root })).toThrow("does not identify its source");
	} finally {
		rmSync(root, { recursive: true, force: true });
	}
});
