#!/usr/bin/env bun

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, posix, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");

type DocMeta = {
	readonly title: string;
	readonly description: string;
	readonly order: number;
	readonly section: string;
};

const DUPLICATED_ROOT_DOCS = {
	"CONTRIBUTING.md": {
		title: "Contributing",
		description: "How to contribute to Signet.",
		order: 24,
		section: "Project",
	},
	"ROADMAP.md": {
		title: "Roadmap",
		description: "Current focus and planned features.",
		order: 25,
		section: "Project",
	},
} satisfies Record<string, DocMeta>;

const REPO_BLOB_BASE = "https://github.com/Signet-AI/signetai/blob/main";

function read(relPath: string): string {
	const abs = join(ROOT, relPath);
	if (!existsSync(abs)) {
		throw new Error(`Missing required file: ${relPath}`);
	}
	return readFileSync(abs, "utf8");
}

function renderFrontmatter(meta: DocMeta): string {
	return [
		"---",
		`title: "${meta.title}"`,
		`description: "${meta.description}"`,
		`order: ${meta.order}`,
		`section: "${meta.section}"`,
		"---",
	].join("\n");
}

function maskCodeSegments(body: string): {
	readonly masked: string;
	readonly restore: (input: string) => string;
} {
	const segments: string[] = [];
	const masked = body.replace(/```[\s\S]*?```|`[^`\n]+`/g, (match) => {
		const index = segments.push(match) - 1;
		return `__SIGNET_DOC_CODE_${index}__`;
	});

	return {
		masked,
		restore: (input: string) =>
			input.replace(/__SIGNET_DOC_CODE_(\d+)__/g, (_full, rawIndex: string) => {
				const index = Number(rawIndex);
				return segments[index] ?? "";
			}),
	};
}

function rewriteMarkdownLinks(sourceName: string, body: string): string {
	const sourceDir = dirname(sourceName);
	const targetDir = posix.join("docs", posix.dirname(sourceName));
	const { masked, restore } = maskCodeSegments(body);

	return restore(
		masked.replace(/(?<!!)\[([^\]]+)\]\(([^)]+)\)/g, (full, text: string, href: string) => {
			if (
				href.startsWith("#") ||
				href.startsWith("http://") ||
				href.startsWith("https://") ||
				href.startsWith("mailto:")
			) {
				return full;
			}

			const [rawPath, hash = ""] = href.split("#", 2);
			if (!rawPath.endsWith(".md") && !rawPath.endsWith(".mdx")) return full;

			const sourceTarget = posix.normalize(posix.join(sourceDir, rawPath));
			const docsTarget = sourceTarget.startsWith("docs/")
				? sourceTarget
				: Object.hasOwn(DUPLICATED_ROOT_DOCS, sourceTarget)
					? posix.join("docs", sourceTarget)
					: undefined;

			const suffix = hash ? `#${hash}` : "";
			if (docsTarget) {
				const nextHref = posix.relative(targetDir, docsTarget) || ".";
				return `[${text}](${nextHref}${suffix})`;
			}

			return `[${text}](${REPO_BLOB_BASE}/${sourceTarget}${suffix})`;
		}),
	);
}

function renderDerivedDoc(name: string, meta: DocMeta, body: string): string {
	const source = rewriteMarkdownLinks(name, body).trimEnd();
	return `${renderFrontmatter(meta)}

<!-- GENERATED FROM /${name} by \`bun scripts/sync-root-docs.ts\`. Do not edit this file directly. -->

${source}
`;
}

function parseArgs(argv: string[]): { readonly check: boolean } {
	if (argv.length === 0) return { check: false };
	if (argv.length === 1 && argv[0] === "--check") return { check: true };
	throw new Error("Usage: bun scripts/sync-root-docs.ts [--check]");
}

function findDuplicatedRootDocs(): string[] {
	const rootNames = new Set(readdirSync(ROOT).filter((name) => name.endsWith(".md") && existsSync(join(ROOT, name))));
	const docsDir = join(ROOT, "docs");
	const docNames = new Set(
		readdirSync(docsDir).filter((name) => name.endsWith(".md") && existsSync(join(docsDir, name))),
	);

	return [...rootNames].filter((name) => docNames.has(name)).sort();
}

function main(): number {
	const args = parseArgs(process.argv.slice(2));
	const duplicates = findDuplicatedRootDocs();
	const configured = Object.keys(DUPLICATED_ROOT_DOCS).sort();
	const missingConfig = duplicates.filter((name) => !configured.includes(name));
	const staleConfig = configured.filter((name) => !duplicates.includes(name));

	if (missingConfig.length > 0 || staleConfig.length > 0) {
		const lines = ["Duplicated root-doc config is out of sync."];
		if (missingConfig.length > 0) {
			lines.push("Missing config for duplicated docs:");
			for (const name of missingConfig) lines.push(`- ${name}`);
		}
		if (staleConfig.length > 0) {
			lines.push("Configured files are no longer duplicated:");
			for (const name of staleConfig) lines.push(`- ${name}`);
		}
		throw new Error(lines.join("\n"));
	}

	const changed: string[] = [];

	for (const [name, meta] of Object.entries(DUPLICATED_ROOT_DOCS)) {
		const sourcePath = name;
		const targetPath = join("docs", name);
		const next = renderDerivedDoc(name, meta, read(sourcePath));
		const current = existsSync(join(ROOT, targetPath)) ? read(targetPath) : "";

		if (current === next) continue;

		changed.push(targetPath);
		if (!args.check) writeFileSync(join(ROOT, targetPath), next);
	}

	if (changed.length === 0) {
		console.log("Root-derived docs are in sync.");
		return 0;
	}

	if (args.check) {
		console.error("Root-derived docs are out of sync:");
		for (const file of changed) console.error(`- ${file}`);
		console.error("Run: bun scripts/sync-root-docs.ts");
		return 1;
	}

	console.log("Updated root-derived docs:");
	for (const file of changed) console.log(`- ${file}`);
	return 0;
}

try {
	process.exit(main());
} catch (err) {
	const msg = err instanceof Error ? err.message : String(err);
	console.error(msg);
	process.exit(2);
}
