#!/usr/bin/env bun

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, posix, relative, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const DOCS_CONTENT = join(ROOT, "web/docs/src/content/docs");
const REPO_BLOB_BASE = "https://github.com/Signet-AI/signetai/blob/main";

type DerivedDoc = {
	readonly title: string;
	readonly description: string;
	readonly target: string;
};

const ROOT_DERIVED_DOCS = {
	"CONTRIBUTING.md": {
		title: "Contributing",
		description: "How to contribute to Signet.",
		target: "web/docs/src/content/docs/contributing.md",
	},
	"ROADMAP.md": {
		title: "Roadmap",
		description: "Current focus and planned features.",
		target: "web/docs/src/content/docs/roadmap.md",
	},
} satisfies Record<string, DerivedDoc>;

function read(path: string): string {
	const absolute = join(ROOT, path);
	if (!existsSync(absolute)) throw new Error(`Missing required file: ${path}`);
	return readFileSync(absolute, "utf8");
}

function contentFiles(dir: string): readonly string[] {
	const files: string[] = [];
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		const path = join(dir, entry.name);
		if (entry.isDirectory()) files.push(...contentFiles(path));
		else if (entry.name.endsWith(".md") || entry.name.endsWith(".mdx")) files.push(path);
	}
	return files;
}

function routeFor(path: string): string {
	const id = relative(DOCS_CONTENT, path)
		.split("\\")
		.join("/")
		.replace(/\.mdx?$/, "");
	return id === "index" ? "/" : `/${id.replace(/\/index$/, "")}/`;
}

function buildPublicRoutes(): ReadonlyMap<string, string> {
	const candidates = contentFiles(DOCS_CONTENT)
		.map((path) => ({ path, route: routeFor(path) }))
		.sort((a, b) => a.route.split("/").length - b.route.split("/").length || a.route.localeCompare(b.route));
	const routes = new Map<string, string>();
	for (const candidate of candidates) {
		const name = candidate.path
			.split("/")
			.at(-1)
			?.replace(/\.mdx?$/, "")
			.toLowerCase();
		if (name && !routes.has(name)) routes.set(name, candidate.route);
	}
	return routes;
}

function renderFrontmatter(doc: DerivedDoc): string {
	return ["---", `title: "${doc.title}"`, `description: "${doc.description}"`, "---"].join("\n");
}

function maskCode(body: string): { readonly text: string; readonly restore: (value: string) => string } {
	const segments: string[] = [];
	const text = body.replace(/```[\s\S]*?```|`[^`\n]+`/g, (match) => {
		const index = segments.push(match) - 1;
		return `__SIGNET_DOC_CODE_${index}__`;
	});
	return {
		text,
		restore: (value: string) =>
			value.replace(/__SIGNET_DOC_CODE_(\d+)__/g, (_match, index: string) => segments[Number(index)] ?? ""),
	};
}

function normalizeRepoPath(source: string, target: string): string {
	return posix.normalize(posix.join(posix.dirname(source), target));
}

function rewriteMarkdownLinks(source: string, body: string, routes: ReadonlyMap<string, string>): string {
	const { text, restore } = maskCode(body);
	return restore(
		text.replace(/(?<!!)\[([^\]]+)\]\(([^)]+)\)/g, (full, label: string, href: string) => {
			if (
				href.startsWith("#") ||
				href.startsWith("http://") ||
				href.startsWith("https://") ||
				href.startsWith("mailto:")
			)
				return full;
			const [rawPath, hash = ""] = href.split("#", 2);
			if (!rawPath.endsWith(".md") && !rawPath.endsWith(".mdx")) return full;
			const target = normalizeRepoPath(source, rawPath);
			const name =
				target
					.split("/")
					.at(-1)
					?.replace(/\.mdx?$/, "")
					.toLowerCase() ?? "";
			const suffix = hash ? `#${hash}` : "";
			const publicRoute = routes.get(name);
			if (publicRoute) return `[${label}](${publicRoute}${suffix})`;
			return `[${label}](${REPO_BLOB_BASE}/${target}${suffix})`;
		}),
	);
}

function renderDerivedDoc(source: string, doc: DerivedDoc, routes: ReadonlyMap<string, string>): string {
	const body = rewriteMarkdownLinks(source, read(source), routes).trimEnd();
	return `${renderFrontmatter(doc)}

<!-- GENERATED FROM /${source} by \`bun scripts/sync-root-docs.ts\`. Do not edit this file directly. -->

${body}
`;
}

function parseArgs(args: readonly string[]): { readonly check: boolean } {
	if (args.length === 0) return { check: false };
	if (args.length === 1 && args[0] === "--check") return { check: true };
	throw new Error("Usage: bun scripts/sync-root-docs.ts [--check]");
}

function main(): number {
	const args = parseArgs(process.argv.slice(2));
	const routes = buildPublicRoutes();
	const changed: string[] = [];

	for (const [source, doc] of Object.entries(ROOT_DERIVED_DOCS)) {
		const next = renderDerivedDoc(source, doc, routes);
		const current = existsSync(join(ROOT, doc.target)) ? read(doc.target) : "";
		if (next === current) continue;
		changed.push(doc.target);
		if (!args.check) writeFileSync(join(ROOT, doc.target), next);
	}

	if (changed.length === 0) {
		console.log("Root-derived docs are in sync.");
		return 0;
	}
	if (args.check) {
		console.error("Root-derived docs are out of sync:");
		for (const path of changed) console.error(`- ${path}`);
		console.error("Run: bun scripts/sync-root-docs.ts");
		return 1;
	}
	console.log("Updated root-derived docs:");
	for (const path of changed) console.log(`- ${path}`);
	return 0;
}

try {
	process.exit(main());
} catch (error) {
	console.error(error instanceof Error ? error.message : String(error));
	process.exit(2);
}
