import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
	VERSION_SYNC_PACKAGE_GLOBS,
	collectCargoLockMismatches,
	findCargoLockPackageVersion,
	resolveWorkspaceDependencyVersions,
} from "./version-sync";

describe("version-sync", () => {
	test("keeps web workspace manifests out of Signet release version sync", () => {
		expect(VERSION_SYNC_PACKAGE_GLOBS).not.toContain("web/**/package.json");
	});

	test("aligns checked-in publishable workspace dependency specs before release installs", () => {
		const raw = `{
  "name": "@signetai/signet-memory-openclaw",
  "version": "0.115.1",
  "publishConfig": {
    "access": "public"
  },
  "dependencies": {
    "@signet/native": "workspace:*",
    "@sinclair/typebox": "0.34.47"
  },
  "devDependencies": {
    "@signet/core": "0.115.1",
    "@signet/sdk": "workspace:^",
    "@types/node": "^22.0.0"
  },
  "peerDependencies": {
    "@signet/plugin": "workspace:~",
    "openclaw": ">=0.1.0"
  }
}
`;

		const next = resolveWorkspaceDependencyVersions(
			raw,
			new Set(["@signet/core", "@signet/sdk", "@signet/plugin", "@signet/native"]),
			"0.115.2",
		);
		const parsed = JSON.parse(next) as {
			devDependencies: Record<string, string>;
			dependencies: Record<string, string>;
			peerDependencies: Record<string, string>;
		};

		expect(parsed.devDependencies["@signet/core"]).toBe("0.115.2");
		expect(parsed.devDependencies["@signet/sdk"]).toBe("^0.115.2");
		expect(parsed.devDependencies["@types/node"]).toBe("^22.0.0");
		expect(parsed.dependencies["@signet/native"]).toBe("0.115.2");
		expect(parsed.dependencies["@sinclair/typebox"]).toBe("0.34.47");
		expect(parsed.peerDependencies["@signet/plugin"]).toBe("~0.115.2");
		expect(parsed.peerDependencies.openclaw).toBe(">=0.1.0");
	});

	test("preserves concrete workspace dependency range operators", () => {
		const raw = `{
  "name": "@signet/example",
  "version": "0.115.1",
  "publishConfig": {
    "access": "public"
  },
  "dependencies": {
    "@signet/core": "^0.115.1",
    "@signet/sdk": "~0.115.1",
    "@signet/connector-base": "0.115.1"
  }
}
`;

		const next = resolveWorkspaceDependencyVersions(
			raw,
			new Set(["@signet/core", "@signet/sdk", "@signet/connector-base"]),
			"0.115.2",
		);
		const parsed = JSON.parse(next) as { dependencies: Record<string, string> };

		expect(parsed.dependencies["@signet/core"]).toBe("^0.115.2");
		expect(parsed.dependencies["@signet/sdk"]).toBe("~0.115.2");
		expect(parsed.dependencies["@signet/connector-base"]).toBe("0.115.2");
	});

	test("reads local package versions from Cargo.lock entries", () => {
		const lock = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "signet-daemon"
version = "0.82.5"
dependencies = [
 "signet-core",
]
`;

		expect(findCargoLockPackageVersion(lock, "signet-daemon")).toBe("0.82.5");
		expect(findCargoLockPackageVersion(lock, "signet-native")).toBeNull();
	});

	test("flags stale Cargo.lock versions for workspace packages", () => {
		const root = mkdtempSync(join(tmpdir(), "signet-version-sync-"));
		try {
			const workspace = join(root, "platform", "daemon-rs");
			const crateDir = join(workspace, "crates", "signet-daemon");
			const crate = join(crateDir, "Cargo.toml");
			mkdirSync(crateDir, { recursive: true });
			writeFileSync(
				join(workspace, "Cargo.toml"),
				`[workspace.package]
version = "0.115.1"
`,
			);
			writeFileSync(
				crate,
				`[package]
name = "signet-daemon"
version.workspace = true
`,
			);
			writeFileSync(
				join(workspace, "Cargo.lock"),
				`version = 4

[[package]]
name = "signet-daemon"
version = "0.82.5"
`,
			);

			expect(collectCargoLockMismatches([crate], "0.115.1")).toEqual([
				`${join(workspace, "Cargo.lock")} package signet-daemon (0.82.5)`,
			]);
		} finally {
			rmSync(root, { force: true, recursive: true });
		}
	});
});
